"use client";

import React, { useState, useEffect } from "react";
import { ActivityDoc } from "@/src/lib/firebase/coursesService";
import { formatPdfEmbedUrl, formatYouTubeUrl, parseLatexSegments } from "@/src/lib/utils/formatters";
import { HomeworkUploader } from "@/src/components/student/HomeworkUploader";
import Lightbox from "yet-another-react-lightbox";
import Zoom from "yet-another-react-lightbox/plugins/zoom";
import Counter from "yet-another-react-lightbox/plugins/counter";
import "yet-another-react-lightbox/styles.css";
import "yet-another-react-lightbox/plugins/counter.css";
import katex from "katex";
import "katex/dist/katex.min.css";
import {
  BookOpen,
  Dumbbell,
  Trophy,
  Video,
  FileText,
  HelpCircle,
  Eye,
  CheckCircle2,
  XCircle,
  X,
  ExternalLink,
  Upload,
  Maximize2,
  Minimize2,
  Sparkles,
  Send,
  Image as ImageIcon,
  Bot,
  User,
  Layers,
  Loader2,
  Plus,
  ZoomIn,
  Paperclip,
  ChevronRight,
  ChevronLeft,
} from "lucide-react";

export interface ChatMessage {
  id: string;
  sender: "ai" | "student";
  text: string;
  images?: string[];
  timestamp: string;
}

/**
 * Helper component that parses LaTeX math formulas wrapped in $...$ or $$...$$
 * inside HTML text strings generated by Quill / Rich Text Editor.
 */
export function MathText({ content, className = "" }: { content?: string; className?: string }) {
  if (!content) return null;

  // Task A: Clean non-breaking spaces generated by Quill Editor (&nbsp; / &#160;)
  const sanitizedContent = content
    .replace(/&nbsp;/g, " ")
    .replace(/&#160;/g, " ");

  try {
    // 1. Process Block Math $$...$$
    let processed = sanitizedContent.replace(/\$\$([\s\S]*?)\$\$/g, (_, math) => {
      try {
        const cleanMath = math
          .replace(/&nbsp;/g, " ")
          .replace(/&#160;/g, " ")
          .replace(/&lt;/g, "<")
          .replace(/&gt;/g, ">")
          .replace(/&amp;/g, "&")
          .trim();
        const rendered = katex.renderToString(cleanMath, {
          displayMode: true,
          throwOnError: false,
        });
        return `<div dir="ltr" class="flex justify-center my-2 font-sans tracking-normal">${rendered}</div>`;
      } catch {
        return `$$${math}$$`;
      }
    });

    // 2. Process Inline Math $...$
    processed = processed.replace(/\$([\s\S]*?)\$/g, (_, math) => {
      try {
        const cleanMath = math
          .replace(/&nbsp;/g, " ")
          .replace(/&#160;/g, " ")
          .replace(/&lt;/g, "<")
          .replace(/&gt;/g, ">")
          .replace(/&amp;/g, "&")
          .trim();
        const rendered = katex.renderToString(cleanMath, {
          displayMode: false,
          throwOnError: false,
        });
        return `<span dir="ltr" class="inline-block mx-1 font-sans tracking-normal">${rendered}</span>`;
      } catch {
        return `$${math}$`;
      }
    });

    return (
      <div
        dir="rtl"
        className={`leading-relaxed rich-text-content whitespace-pre-wrap ${className}`}
        dangerouslySetInnerHTML={{ __html: processed }}
      />
    );
  } catch (error) {
    console.error("Error rendering MathText:", error);
    return (
      <div dir="rtl" className={`leading-relaxed rich-text-content whitespace-pre-wrap ${className}`}>
        {content}
      </div>
    );
  }
}

interface StudentPreviewProps {
  activity: ActivityDoc;
  courseTitle?: string;
}

export function StudentPreview({ activity, courseTitle }: StudentPreviewProps) {
  // PDF Preview Modal State & Full Screen Toggle
  const [selectedPdfUrl, setSelectedPdfUrl] = useState<string | null>(null);
  const [isFullScreen, setIsFullScreen] = useState(false);

  // Station Navigation State & Socratic AI Chat State
  const stationsList =
    activity.stations && activity.stations.length > 0
      ? activity.stations
      : [
          {
            id: "station_default",
            order: 1,
            title: "المحطة 1: التفاعل الشامل",
            content: activity.description || activity.title || "تفضل بحل التمرين المطلوب واستعمال المساعد الذكي سقراطياً.",
            aiDirectives: "ساعد التلميذ في استيعاب مفاهيم المحطة خطوة بخطوة.",
          },
        ];

  const [activeStationIndex, setActiveStationIndex] = useState<number>(0);
  const currentStation = stationsList[activeStationIndex] || stationsList[0];

  // Chat messages keyed by station ID
  const [stationChats, setStationChats] = useState<Record<string, ChatMessage[]>>({});
  const [inputText, setInputText] = useState("");
  const [attachedImages, setAttachedImages] = useState<string[]>([]);
  const [showImageUploader, setShowImageUploader] = useState(false);
  const [isAiThinking, setIsAiThinking] = useState(false);

  // Lightbox State for Chat Images
  const [chatLightboxOpen, setChatLightboxOpen] = useState(false);
  const [chatLightboxIndex, setChatLightboxIndex] = useState(0);
  const [chatLightboxSlides, setChatLightboxSlides] = useState<Array<{ src: string }>>([]);

  // Auto-initialize Socratic AI Greeting for active station
  useEffect(() => {
    const stId = currentStation.id || `st_${activeStationIndex}`;
    if (!stationChats[stId] || stationChats[stId].length === 0) {
      const initialGreeting: ChatMessage = {
        id: `msg_init_${stId}`,
        sender: "ai",
        text: `مرحباً بك في **${currentStation.title || `المحطة #${activeStationIndex + 1}`}**! 👋\n\n**المهمة الحالية للوكيل المطلوب إنجازها:**\n${currentStation.content || "قم بحل المطلوب وتزويد المساعد الذكي بإجابتك"}\n\nاكتب إجابتك أو أرفق صورة لحلك اليدوي لمراجعتها وتوجيهك سقراطياً!`,
        timestamp: new Date().toLocaleTimeString("ar-EG", { hour: "2-digit", minute: "2-digit" }),
      };
      setStationChats((prev) => ({
        ...prev,
        [stId]: [initialGreeting],
      }));
    }
  }, [activeStationIndex, currentStation]);

  const handleSendMessage = () => {
    if (!inputText.trim() && attachedImages.length === 0) return;

    const stId = currentStation.id || `st_${activeStationIndex}`;
    const userMsg: ChatMessage = {
      id: `msg_user_${Date.now()}`,
      sender: "student",
      text: inputText.trim(),
      images: [...attachedImages],
      timestamp: new Date().toLocaleTimeString("ar-EG", { hour: "2-digit", minute: "2-digit" }),
    };

    setStationChats((prev) => ({
      ...prev,
      [stId]: [...(prev[stId] || []), userMsg],
    }));

    setInputText("");
    setAttachedImages([]);
    setShowImageUploader(false);
    setIsAiThinking(true);

    setTimeout(() => {
      let aiText = `أحسنت في هذه الإجابة! 👏 دعنا نناقش خطوتك في **${currentStation.title || `المحطة #${activeStationIndex + 1}`}** سقراطياً:`;

      if (userMsg.images && userMsg.images.length > 0) {
        aiText += `\n\nلقد قمت بفحص صورة حلك اليدوي المرفقة (${userMsg.images.length} صورة). خطوات الكتابة واضحة وممتازة!`;
      }

      if (currentStation.aiDirectives) {
        aiText += `\n\n💡 **توجيه الوكيل المميز:** تم تطبيق التوجيهات الخاصة بالنشاط. هل يمكنك مراجعة خطوة الحساب الأولى للتأكد من النتيجة؟`;
      } else {
        aiText += `\n\nخطواتك دقيقة، هل تود الانتقال إلى المحطة التالية أم نراجع هذه الخطوة بالتفصيل؟`;
      }

      const aiMsg: ChatMessage = {
        id: `msg_ai_${Date.now()}`,
        sender: "ai",
        text: aiText,
        timestamp: new Date().toLocaleTimeString("ar-EG", { hour: "2-digit", minute: "2-digit" }),
      };

      setStationChats((prev) => ({
        ...prev,
        [stId]: [...(prev[stId] || []), aiMsg],
      }));
      setIsAiThinking(false);
    }, 1200);
  };

  const handleOpenChatImage = (images: string[], index: number) => {
    setChatLightboxSlides(images.map((img) => ({ src: img })));
    setChatLightboxIndex(index);
    setChatLightboxOpen(true);
  };

  // Student Interactive Quiz Test State
  const [userAnswers, setUserAnswers] = useState<Record<number, number>>({});
  const [submittedQuiz, setSubmittedQuiz] = useState(false);

  let TypeIcon = BookOpen;
  let typeLabel = "درس نظرى";
  let badgeStyle = "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20";

  if (activity.type === "practice") {
    TypeIcon = Dumbbell;
    typeLabel = "تطبيق / تمرين";
    badgeStyle = "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20";
  } else if (activity.type === "exam") {
    TypeIcon = Trophy;
    typeLabel = "امتحان / تقييم";
    badgeStyle = "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20";
  }

  const handleSelectAnswer = (qIndex: number, optionIdx: number) => {
    if (submittedQuiz) return;
    setUserAnswers((prev) => ({
      ...prev,
      [qIndex]: optionIdx,
    }));
  };

  const calculateScore = () => {
    if (!activity.quiz) return 0;
    let score = 0;
    activity.quiz.forEach((q: any, idx: number) => {
      if (userAnswers[idx] === q.correctIndex) {
        score += 1;
      }
    });
    return score;
  };

  return (
    <div className="space-y-6 animate-fadeIn max-w-4xl mx-auto" dir="rtl">
      {/* Student View Banner Header */}
      <div className="p-4 rounded-2xl bg-primary/10 border border-primary/20 text-primary flex items-center justify-between text-xs font-bold shadow-xs">
        <div className="flex items-center gap-2">
          <Eye className="w-4 h-4" />
          <span>وضع المعاينة التفاعلية كطالب (Student Preview Mode)</span>
        </div>
        <span className="text-[11px] font-normal text-on-surface-variant">
          يظهر هذا العرض تماماً كما يشاهده التلميذ في منصته
        </span>
      </div>

      {/* Main Student Card */}
      <div className="bg-surface border border-outline/15 rounded-3xl p-6 sm:p-8 shadow-sm space-y-6">
        {/* Activity Header */}
        <div className="space-y-3 border-b border-outline/10 pb-6">
          <div className="flex items-center gap-2 flex-wrap">
            <span className={`text-xs font-extrabold px-3 py-1 rounded-xl border flex items-center gap-1.5 ${badgeStyle}`}>
              <TypeIcon className="w-4 h-4" />
              <span>{typeLabel}</span>
            </span>
            {courseTitle && (
              <span className="text-xs font-semibold text-on-surface-variant/80">
                مادة: {courseTitle}
              </span>
            )}
          </div>

          <h1 className="text-2xl sm:text-3xl font-extrabold text-on-surface tracking-tight">
            <MathText content={activity.title} />
          </h1>

          {activity.description && (
            <div className="text-sm text-on-surface-variant/90 leading-relaxed bg-surface-variant/20 p-4 rounded-2xl border border-outline/10">
              <MathText content={activity.description} />
            </div>
          )}
        </div>

        {/* Video Embeds Section (using formatYouTubeUrl) */}
        {activity.videos && activity.videos.length > 0 && (
          <div className="space-y-3 pt-2">
            <h3 className="text-base font-bold text-on-surface flex items-center gap-2">
              <Video className="w-5 h-5 text-primary" />
              <span>فيديوهات الدرس (الشرح التفاعلي)</span>
            </h3>

            <div className="grid grid-cols-1 gap-4">
              {activity.videos.map((vidUrl, idx) => (
                <div key={idx} className="p-4 rounded-2xl bg-surface-variant/30 border border-outline/15 space-y-2">
                  <div className="flex items-center justify-between text-xs font-bold text-on-surface">
                    <span>فيديو الشرح رقم {idx + 1}</span>
                    <a
                      href={vidUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-primary hover:underline flex items-center gap-1 text-[11px]"
                    >
                      <span>فتح الفيديو في النافذة الأصلية</span>
                      <ExternalLink className="w-3.5 h-3.5" />
                    </a>
                  </div>
                  <div className="aspect-video w-full rounded-xl overflow-hidden bg-black/90 flex items-center justify-center border border-outline/10 shadow-inner">
                    <iframe
                      src={formatYouTubeUrl(vidUrl)}
                      title={`فيديو ${idx + 1}`}
                      className="w-full h-full"
                      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share; fullscreen"
                      allowFullScreen
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* PDF Attachments Section */}
        {activity.attachments && activity.attachments.length > 0 && (
          <div className="space-y-3 pt-2">
            <h3 className="text-base font-bold text-on-surface flex items-center gap-2">
              <FileText className="w-5 h-5 text-secondary" />
              <span>المرفقات والملخصات (PDF / Drive)</span>
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {activity.attachments.map((item, idx) => {
                const url = typeof item === "string" ? item : item.url;
                const title = typeof item === "string" ? `الملف المرفق ${idx + 1} (PDF)` : item.title || `الملف المرفق ${idx + 1}`;
                return (
                  <div
                    key={idx}
                    onClick={() => {
                      setSelectedPdfUrl(url);
                      setIsFullScreen(false);
                    }}
                    className="p-4 rounded-2xl bg-surface-variant/30 border border-outline/15 hover:border-primary/40 hover:bg-surface-variant/50 transition-all cursor-pointer flex items-center justify-between gap-3 group"
                  >
                    <div className="flex items-center gap-3 truncate">
                      <div className="w-10 h-10 rounded-xl bg-secondary/10 text-secondary flex items-center justify-center shrink-0">
                        <FileText className="w-5 h-5" />
                      </div>
                      <div className="truncate">
                        <span className="text-xs font-bold text-on-surface group-hover:text-primary transition-colors block truncate">
                          {title}
                        </span>
                        <span className="text-[10px] text-on-surface-variant/70">اضغط للمعاينة الفورية</span>
                      </div>
                    </div>

                    <Eye className="w-4 h-4 text-on-surface-variant/70 group-hover:text-primary transition-colors shrink-0" />
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Dynamic Station-by-Station AI Chat Interface (Socratic Navigation) */}
        <div className="space-y-4 pt-4 border-t border-outline/10">
          <div className="p-5 rounded-3xl bg-surface-variant/20 border border-outline/15 space-y-4 shadow-sm">
            {/* Header & Station Navigation Progress */}
            <div className="space-y-3">
              <div className="flex items-center justify-between flex-wrap gap-2">
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-xl bg-primary/10 text-primary flex items-center justify-center font-bold">
                    <Sparkles className="w-4 h-4" />
                  </div>
                  <div>
                    <h3 className="text-sm font-extrabold text-on-surface">المساعد الذكي السقراطي - المحطات التفاعلية</h3>
                    <p className="text-[11px] text-on-surface-variant">تنقل بين محطات النشاط وناقش حلك خطوة بخطوة مع الذكاء الاصطناعي</p>
                  </div>
                </div>

                <div className="flex items-center gap-2 text-xs font-extrabold text-primary bg-primary/10 px-3 py-1.5 rounded-xl border border-primary/20">
                  <Layers className="w-3.5 h-3.5" />
                  <span>المحطة الحالية: {activeStationIndex + 1} من {stationsList.length}</span>
                </div>
              </div>

              {/* Progress Bar */}
              <div className="w-full h-2 rounded-full bg-surface-variant/60 overflow-hidden">
                <div
                  className="h-full bg-primary transition-all duration-500 rounded-full"
                  style={{ width: `${((activeStationIndex + 1) / stationsList.length) * 100}%` }}
                />
              </div>

              {/* Station Navigation Pills/Tabs */}
              <div className="flex items-center gap-2 overflow-x-auto pb-1 scrollbar-thin">
                {stationsList.map((st, idx) => {
                  const isActive = idx === activeStationIndex;
                  return (
                    <button
                      key={st.id || idx}
                      type="button"
                      onClick={() => setActiveStationIndex(idx)}
                      className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all shrink-0 flex items-center gap-1.5 border ${
                        isActive
                          ? "bg-primary text-on-primary border-primary shadow-xs"
                          : "bg-surface text-on-surface-variant border-outline/20 hover:border-primary/40"
                      }`}
                    >
                      <span className="w-4 h-4 rounded-full bg-surface/20 flex items-center justify-center text-[10px]">
                        {idx + 1}
                      </span>
                      <span className="truncate max-w-[150px]">{st.title || `المحطة ${idx + 1}`}</span>
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Active Station Focus / Task Card */}
            <div className="p-4 rounded-2xl bg-indigo-500/10 border border-indigo-500/20 space-y-1">
              <span className="text-[11px] font-extrabold text-indigo-700 dark:text-indigo-300 block">
                المهمة المطلوبة في {currentStation.title || `المحطة #${activeStationIndex + 1}`}:
              </span>
              <div className="text-xs font-medium text-on-surface">
                <MathText content={currentStation.content} />
              </div>
            </div>

            {/* Station AI Chat Area */}
            <div className="space-y-3">
              {/* Chat Messages Timeline */}
              <div className="p-4 rounded-2xl bg-surface border border-outline/15 max-h-[420px] overflow-y-auto space-y-4 shadow-inner">
                {((currentStation.id && stationChats[currentStation.id]) || stationChats[`st_${activeStationIndex}`] || []).map((msg) => {
                  const isAi = msg.sender === "ai";
                  return (
                    <div
                      key={msg.id}
                      className={`flex gap-3 items-start ${isAi ? "justify-start" : "justify-end"}`}
                    >
                      {isAi && (
                        <div className="w-8 h-8 rounded-xl bg-indigo-500/10 text-indigo-500 flex items-center justify-center shrink-0 border border-indigo-500/20">
                          <Bot className="w-4 h-4" />
                        </div>
                      )}

                      <div
                        className={`max-w-[85%] sm:max-w-[75%] p-4 rounded-2xl space-y-2 text-xs leading-relaxed ${
                          isAi
                            ? "bg-indigo-500/10 border border-indigo-500/20 text-on-surface rounded-tr-xs shadow-2xs"
                            : "bg-primary text-on-primary rounded-tl-xs shadow-xs"
                        }`}
                      >
                        <div className="font-medium whitespace-pre-line">
                          <MathText content={msg.text} />
                        </div>

                        {/* Student Attached Images Grid */}
                        {msg.images && msg.images.length > 0 && (
                          <div className="grid grid-cols-2 gap-2 pt-2 border-t border-outline/10">
                            {msg.images.map((imgUrl, imgIdx) => (
                              <div
                                key={imgIdx}
                                onClick={() => handleOpenChatImage(msg.images!, imgIdx)}
                                className="group relative aspect-4/3 rounded-xl overflow-hidden border border-outline/20 bg-surface cursor-pointer shadow-2xs"
                              >
                                <img src={imgUrl} alt="صورة الحل" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300" />
                                <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center text-white text-[10px] font-bold gap-1">
                                  <ZoomIn className="w-3.5 h-3.5" />
                                  <span>تكبير</span>
                                </div>
                              </div>
                            ))}
                          </div>
                        )}

                        <span className={`text-[9px] block text-left ${isAi ? "text-on-surface-variant/70" : "text-on-primary/80"}`}>
                          {msg.timestamp}
                        </span>
                      </div>

                      {!isAi && (
                        <div className="w-8 h-8 rounded-xl bg-primary text-on-primary flex items-center justify-center shrink-0">
                          <User className="w-4 h-4" />
                        </div>
                      )}
                    </div>
                  );
                })}

                {/* AI Thinking Indicator */}
                {isAiThinking && (
                  <div className="flex items-center gap-2.5 p-3 rounded-2xl bg-indigo-500/10 border border-indigo-500/20 text-indigo-600 dark:text-indigo-400 text-xs font-bold max-w-fit">
                    <Loader2 className="w-4 h-4 animate-spin" />
                    <span>جاري تحليل إجابتك وسياق المحطة بواسطة المساعد الذكي...</span>
                  </div>
                )}
              </div>

              {/* Attached Images Preview Bar */}
              {attachedImages.length > 0 && (
                <div className="p-3 rounded-2xl bg-surface border border-outline/20 space-y-2">
                  <span className="text-[11px] font-bold text-on-surface flex items-center gap-1.5">
                    <ImageIcon className="w-3.5 h-3.5 text-primary" />
                    <span>الصور المرفقة المعينة للإرسال: ({attachedImages.length})</span>
                  </span>
                  <div className="flex flex-wrap gap-2">
                    {attachedImages.map((url, idx) => (
                      <div key={idx} className="relative w-16 h-16 rounded-xl overflow-hidden border border-outline/30 group">
                        <img src={url} alt="مرفق" className="w-full h-full object-cover" />
                        <button
                          type="button"
                          onClick={() => setAttachedImages(attachedImages.filter((_, i) => i !== idx))}
                          className="absolute top-1 left-1 w-5 h-5 rounded-full bg-error text-on-error flex items-center justify-center"
                        >
                          <X className="w-3 h-3" />
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Inline HomeworkUploader Drawer */}
              {showImageUploader && (
                <div className="p-4 rounded-2xl bg-surface border border-outline/20 space-y-2 animate-fadeIn">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-on-surface flex items-center gap-1.5">
                      <ImageIcon className="w-4 h-4 text-primary" />
                      <span>إرفاق صور الحلول اليدوية أو المسودة</span>
                    </span>
                    <button
                      type="button"
                      onClick={() => setShowImageUploader(false)}
                      className="text-on-surface-variant hover:text-on-surface p-1"
                    >
                      <X className="w-4 h-4" />
                    </button>
                  </div>
                  <HomeworkUploader
                    currentUrls={attachedImages}
                    onUploadSuccess={(urls) => {
                      setAttachedImages(urls);
                    }}
                  />
                </div>
              )}

              {/* Bottom Input Controls Bar */}
              <div className="flex items-center gap-2 bg-surface p-2 rounded-2xl border border-outline/25 shadow-2xs">
                <button
                  type="button"
                  onClick={() => setShowImageUploader(!showImageUploader)}
                  className={`h-11 px-3.5 rounded-xl border text-xs font-bold transition-all flex items-center gap-1.5 shrink-0 ${
                    showImageUploader || attachedImages.length > 0
                      ? "bg-primary/10 border-primary text-primary"
                      : "bg-surface-variant/40 border-outline/20 text-on-surface-variant hover:bg-surface-variant"
                  }`}
                  title="إرفاق صورة الحل اليدوي"
                >
                  <ImageIcon className="w-4 h-4" />
                  <span className="hidden sm:inline">إرفاق صورة الحل</span>
                </button>

                <input
                  type="text"
                  value={inputText}
                  onChange={(e) => setInputText(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter" && !e.shiftKey) {
                      e.preventDefault();
                      handleSendMessage();
                    }
                  }}
                  placeholder="اكتب إجابتك أو سؤالك حول هذه المحطة هنا..."
                  className="flex-1 h-11 px-4 rounded-xl bg-surface-variant/30 border border-outline/20 text-on-surface text-xs font-medium focus:outline-none focus:border-primary"
                />

                <button
                  type="button"
                  onClick={handleSendMessage}
                  disabled={!inputText.trim() && attachedImages.length === 0}
                  className="h-11 px-5 rounded-xl bg-primary text-on-primary font-bold text-xs hover:bg-primary/90 transition-all shadow-md flex items-center gap-1.5 shrink-0 disabled:opacity-50"
                >
                  <span>إرسال</span>
                  <Send className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Student Interactive Quiz Section */}
        {activity.hasQuiz && activity.quiz && activity.quiz.length > 0 && (
          <div className="space-y-5 pt-4 border-t border-outline/10">
            <div className="flex items-center justify-between">
              <h3 className="text-base font-bold text-on-surface flex items-center gap-2">
                <HelpCircle className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
                <span>اختبار تفاعلي تجريبي (Quiz)</span>
              </h3>
              {submittedQuiz && (
                <span className="text-xs font-extrabold px-3 py-1 rounded-xl bg-emerald-500/20 text-emerald-700 dark:text-emerald-300">
                  النتيجة: {calculateScore()} / {activity.quiz.length}
                </span>
              )}
            </div>

            <div className="space-y-5">
              {activity.quiz.map((q: any, qIdx: number) => {
                const selectedOpt = userAnswers[qIdx];

                return (
                  <div key={q.id || qIdx} className="p-5 rounded-2xl bg-surface-variant/20 border border-outline/15 space-y-3">
                    <div className="flex items-start gap-2 text-xs font-bold text-on-surface">
                      <span className="w-6 h-6 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0">
                        {qIdx + 1}
                      </span>
                      <div className="pt-0.5">
                        <MathText content={q.question} />
                      </div>
                    </div>

                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 pt-1">
                      {q.options.map((optText: any, oIdx: number) => {
                        const isSelected = selectedOpt === oIdx;
                        const isCorrectOption = q.correctIndex === oIdx;

                        let optCardStyle = "bg-surface border-outline/20 text-on-surface hover:bg-surface-variant/50";

                        if (submittedQuiz) {
                          if (isCorrectOption) {
                            optCardStyle = "bg-emerald-500/20 border-emerald-500 text-emerald-700 font-bold";
                          } else if (isSelected && !isCorrectOption) {
                            optCardStyle = "bg-error-container/60 border-error text-on-error-container font-bold";
                          }
                        } else if (isSelected) {
                          optCardStyle = "bg-primary/10 border-primary text-primary font-bold shadow-xs";
                        }

                        return (
                          <div
                            key={oIdx}
                            onClick={() => handleSelectAnswer(qIdx, oIdx)}
                            className={`p-3 rounded-xl border transition-all cursor-pointer flex items-center justify-between text-xs ${optCardStyle}`}
                          >
                            <span>
                              <MathText content={optText} />
                            </span>
                            {submittedQuiz && isCorrectOption && (
                              <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                            )}
                            {submittedQuiz && isSelected && !isCorrectOption && (
                              <XCircle className="w-4 h-4 text-error shrink-0" />
                            )}
                          </div>
                        );
                      })}
                    </div>

                    {/* Question Explanation after submission */}
                    {submittedQuiz && q.explanation && (
                      <div className="p-3 rounded-xl bg-surface border border-outline/10 text-[11px] text-on-surface-variant mt-2">
                        <strong className="text-primary block mb-0.5">التوضيح الشارح:</strong>
                        <MathText content={q.explanation} />
                      </div>
                    )}
                  </div>
                );
              })}
            </div>

            {/* Quiz Submit Test Button */}
            <div className="pt-2">
              {!submittedQuiz ? (
                <button
                  type="button"
                  onClick={() => setSubmittedQuiz(true)}
                  className="w-full h-11 rounded-xl bg-emerald-600 text-white font-bold text-xs hover:bg-emerald-700 transition-colors shadow-sm"
                >
                  تأكيد الإجابات واختبار النتيجة
                </button>
              ) : (
                <button
                  type="button"
                  onClick={() => {
                    setSubmittedQuiz(false);
                    setUserAnswers({});
                  }}
                  className="w-full h-11 rounded-xl bg-surface-variant text-on-surface-variant font-bold text-xs hover:bg-surface-variant/80 transition-colors"
                >
                  إعادة الاختبار التجريبي
                </button>
              )}
            </div>
          </div>
        )}
      </div>

      {/* Task B: Interactive PDF Modal Preview with Full-Screen Toggle */}
      {selectedPdfUrl && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4 animate-fadeIn">
          <div
            className={`bg-surface border border-outline/15 shadow-2xl flex flex-col space-y-4 transition-all duration-300 ${
              isFullScreen
                ? "fixed inset-0 z-50 w-screen h-screen max-w-none rounded-none m-0 p-4 sm:p-6"
                : "rounded-3xl p-6 max-w-4xl w-full h-[85vh] animate-scaleUp"
            }`}
          >
            <div className="flex items-center justify-between border-b border-outline/10 pb-3">
              <h3 className="text-sm font-bold text-on-surface flex items-center gap-2">
                <FileText className="w-5 h-5 text-secondary" />
                <span>معاينة ملف PDF المرفق</span>
              </h3>

              <div className="flex items-center gap-2">
                {/* Full Screen Toggle Button */}
                <button
                  type="button"
                  onClick={() => setIsFullScreen(!isFullScreen)}
                  className="p-1.5 rounded-xl text-on-surface-variant hover:bg-surface-variant hover:text-primary transition-colors"
                  title={isFullScreen ? "تصغير النافذة" : "ملء الشاشة"}
                  aria-label={isFullScreen ? "تصغير النافذة" : "ملء الشاشة"}
                >
                  {isFullScreen ? <Minimize2 className="w-5 h-5" /> : <Maximize2 className="w-5 h-5" />}
                </button>

                <a
                  href={selectedPdfUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-3 py-1.5 rounded-xl bg-primary/10 text-primary text-xs font-bold hover:bg-primary/20 transition-colors flex items-center gap-1"
                >
                  <span>فتح في نافذة جديدة</span>
                  <ExternalLink className="w-3.5 h-3.5" />
                </a>

                <button
                  type="button"
                  onClick={() => {
                    setSelectedPdfUrl(null);
                    setIsFullScreen(false);
                  }}
                  className="p-1.5 rounded-xl text-on-surface-variant hover:bg-surface-variant transition-colors"
                  aria-label="إغلاق النافذة"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>
            </div>

            <div className="flex-1 w-full rounded-2xl overflow-hidden bg-surface-variant/20 border border-outline/10">
              <iframe
                src={formatPdfEmbedUrl(selectedPdfUrl)}
                allow="autoplay"
                className={`w-full ${isFullScreen ? "h-[calc(100vh-100px)]" : "h-[600px]"} rounded-xl border-none`}
                title="PDF Preview"
              />
            </div>
          </div>
        </div>
      )}

      {/* Lightbox Component for High-Res Zoom on Chat Images */}
      <Lightbox
        open={chatLightboxOpen}
        close={() => setChatLightboxOpen(false)}
        index={chatLightboxIndex}
        slides={chatLightboxSlides}
        plugins={[Zoom, Counter]}
      />
    </div>
  );
}

export default StudentPreview;
