"use client";

import React, { useState } from "react";
import { ActivityDoc } from "@/src/lib/firebase/coursesService";
import { formatPdfEmbedUrl, formatYouTubeUrl, parseLatexSegments } from "@/src/lib/utils/formatters";
import katex from "katex";
import "katex/dist/katex.min.css";
import {
  BookOpen,
  Dumbbell,
  Trophy,
  Video,
  FileText,
  HelpCircle,
  Eye,
  CheckCircle2,
  XCircle,
  X,
  ExternalLink,
  Upload,
  Maximize2,
  Minimize2,
} from "lucide-react";

/**
 * Helper component that parses LaTeX math formulas wrapped in $...$ or $$...$$
 * inside HTML text strings generated by Quill / Rich Text Editor.
 */
export function MathText({ content }: { content?: string }) {
  if (!content) return null;

  // Task A: Clean non-breaking spaces generated by Quill Editor (&nbsp; / &#160;)
  const sanitizedContent = content
    .replace(/&nbsp;/g, " ")
    .replace(/&#160;/g, " ");

  try {
    // 1. Process Block Math $$...$$
    let processed = sanitizedContent.replace(/\$\$([\s\S]*?)\$\$/g, (_, math) => {
      try {
        const cleanMath = math.replace(/&nbsp;/g, " ").replace(/&#160;/g, " ").trim();
        const rendered = katex.renderToString(cleanMath, {
          displayMode: true,
          throwOnError: false,
        });
        return `<div dir="ltr" class="flex justify-center my-2 font-sans tracking-normal">${rendered}</div>`;
      } catch {
        return `$$${math}$$`;
      }
    });

    // 2. Process Inline Math $...$
    processed = processed.replace(/\$([\s\S]*?)\$/g, (_, math) => {
      try {
        const cleanMath = math.replace(/&nbsp;/g, " ").replace(/&#160;/g, " ").trim();
        const rendered = katex.renderToString(cleanMath, {
          displayMode: false,
          throwOnError: false,
        });
        return `<span dir="ltr" class="inline-block mx-1 font-sans tracking-normal">${rendered}</span>`;
      } catch {
        return `$${math}$`;
      }
    });

    return (
      <div
        dir="rtl"
        className="leading-relaxed rich-text-content"
        dangerouslySetInnerHTML={{ __html: processed }}
      />
    );
  } catch (error) {
    console.error("Error rendering MathText:", error);
    return (
      <div dir="rtl" className="leading-relaxed rich-text-content">
        {content}
      </div>
    );
  }
}

interface StudentPreviewProps {
  activity: ActivityDoc;
  courseTitle?: string;
}

export function StudentPreview({ activity, courseTitle }: StudentPreviewProps) {
  // PDF Preview Modal State & Full Screen Toggle
  const [selectedPdfUrl, setSelectedPdfUrl] = useState<string | null>(null);
  const [isFullScreen, setIsFullScreen] = useState(false);

  // Student Interactive Quiz Test State
  const [userAnswers, setUserAnswers] = useState<Record<number, number>>({});
  const [submittedQuiz, setSubmittedQuiz] = useState(false);

  let TypeIcon = BookOpen;
  let typeLabel = "درس نظرى";
  let badgeStyle = "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20";

  if (activity.type === "practice") {
    TypeIcon = Dumbbell;
    typeLabel = "تطبيق / تمرين";
    badgeStyle = "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20";
  } else if (activity.type === "exam") {
    TypeIcon = Trophy;
    typeLabel = "امتحان / تقييم";
    badgeStyle = "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20";
  }

  const handleSelectAnswer = (qIndex: number, optionIdx: number) => {
    if (submittedQuiz) return;
    setUserAnswers((prev) => ({
      ...prev,
      [qIndex]: optionIdx,
    }));
  };

  const calculateScore = () => {
    if (!activity.quiz) return 0;
    let score = 0;
    activity.quiz.forEach((q, idx) => {
      if (userAnswers[idx] === q.correctIndex) {
        score += 1;
      }
    });
    return score;
  };

  return (
    <div className="space-y-6 animate-fadeIn max-w-4xl mx-auto" dir="rtl">
      {/* Student View Banner Header */}
      <div className="p-4 rounded-2xl bg-primary/10 border border-primary/20 text-primary flex items-center justify-between text-xs font-bold shadow-xs">
        <div className="flex items-center gap-2">
          <Eye className="w-4 h-4" />
          <span>وضع المعاينة التفاعلية كطالب (Student Preview Mode)</span>
        </div>
        <span className="text-[11px] font-normal text-on-surface-variant">
          يظهر هذا العرض تماماً كما يشاهده التلميذ في منصته
        </span>
      </div>

      {/* Main Student Card */}
      <div className="bg-surface border border-outline/15 rounded-3xl p-6 sm:p-8 shadow-sm space-y-6">
        {/* Activity Header */}
        <div className="space-y-3 border-b border-outline/10 pb-6">
          <div className="flex items-center gap-2 flex-wrap">
            <span className={`text-xs font-extrabold px-3 py-1 rounded-xl border flex items-center gap-1.5 ${badgeStyle}`}>
              <TypeIcon className="w-4 h-4" />
              <span>{typeLabel}</span>
            </span>
            {courseTitle && (
              <span className="text-xs font-semibold text-on-surface-variant/80">
                مادة: {courseTitle}
              </span>
            )}
          </div>

          <h1 className="text-2xl sm:text-3xl font-extrabold text-on-surface tracking-tight">
            <MathText content={activity.title} />
          </h1>

          {activity.description && (
            <div className="text-sm text-on-surface-variant/90 leading-relaxed bg-surface-variant/20 p-4 rounded-2xl border border-outline/10">
              <MathText content={activity.description} />
            </div>
          )}
        </div>

        {/* Video Embeds Section (using formatYouTubeUrl) */}
        {activity.videos && activity.videos.length > 0 && (
          <div className="space-y-3 pt-2">
            <h3 className="text-base font-bold text-on-surface flex items-center gap-2">
              <Video className="w-5 h-5 text-primary" />
              <span>فيديوهات الدرس (الشرح التفاعلي)</span>
            </h3>

            <div className="grid grid-cols-1 gap-4">
              {activity.videos.map((vidUrl, idx) => (
                <div key={idx} className="p-4 rounded-2xl bg-surface-variant/30 border border-outline/15 space-y-2">
                  <div className="flex items-center justify-between text-xs font-bold text-on-surface">
                    <span>فيديو الشرح رقم {idx + 1}</span>
                    <a
                      href={vidUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-primary hover:underline flex items-center gap-1 text-[11px]"
                    >
                      <span>فتح الفيديو في النافذة الأصلية</span>
                      <ExternalLink className="w-3.5 h-3.5" />
                    </a>
                  </div>
                  <div className="aspect-video w-full rounded-xl overflow-hidden bg-black/90 flex items-center justify-center border border-outline/10 shadow-inner">
                    <iframe
                      src={formatYouTubeUrl(vidUrl)}
                      title={`فيديو ${idx + 1}`}
                      className="w-full h-full"
                      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share; fullscreen"
                      allowFullScreen
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* PDF Attachments Section */}
        {activity.attachments && activity.attachments.length > 0 && (
          <div className="space-y-3 pt-2">
            <h3 className="text-base font-bold text-on-surface flex items-center gap-2">
              <FileText className="w-5 h-5 text-secondary" />
              <span>المرفقات والملخصات (PDF / Drive)</span>
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {activity.attachments.map((item, idx) => {
                const url = typeof item === "string" ? item : item.url;
                const title = typeof item === "string" ? `الملف المرفق ${idx + 1} (PDF)` : item.title || `الملف المرفق ${idx + 1}`;
                return (
                  <div
                    key={idx}
                    onClick={() => {
                      setSelectedPdfUrl(url);
                      setIsFullScreen(false);
                    }}
                    className="p-4 rounded-2xl bg-surface-variant/30 border border-outline/15 hover:border-primary/40 hover:bg-surface-variant/50 transition-all cursor-pointer flex items-center justify-between gap-3 group"
                  >
                    <div className="flex items-center gap-3 truncate">
                      <div className="w-10 h-10 rounded-xl bg-secondary/10 text-secondary flex items-center justify-center shrink-0">
                        <FileText className="w-5 h-5" />
                      </div>
                      <div className="truncate">
                        <span className="text-xs font-bold text-on-surface group-hover:text-primary transition-colors block truncate">
                          {title}
                        </span>
                        <span className="text-[10px] text-on-surface-variant/70">اضغط للمعاينة الفورية</span>
                      </div>
                    </div>

                    <Eye className="w-4 h-4 text-on-surface-variant/70 group-hover:text-primary transition-colors shrink-0" />
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Student Homework Submission Box if required */}
        {activity.requireSubmission && (
          <div className="p-5 rounded-2xl bg-surface-variant/30 border border-outline/15 space-y-3">
            <div className="flex items-center gap-2 text-xs font-bold text-on-surface">
              <Upload className="w-4 h-4 text-primary" />
              <span>تسليم إجابة الطالب (تمرين يتطلب تسليم)</span>
            </div>
            <p className="text-xs text-on-surface-variant/80">
              يتطلب هذا النشاط رفع صور الحل أو ملف PDF لمراجعة الأستاذ وتقييمه.
            </p>
            <div className="p-4 rounded-xl border border-dashed border-outline/30 text-center text-xs font-medium text-on-surface-variant bg-surface">
              [منطقة رفع تسليم إجابة الطالب]
            </div>
          </div>
        )}

        {/* Student Interactive Quiz Section */}
        {activity.hasQuiz && activity.quiz && activity.quiz.length > 0 && (
          <div className="space-y-5 pt-4 border-t border-outline/10">
            <div className="flex items-center justify-between">
              <h3 className="text-base font-bold text-on-surface flex items-center gap-2">
                <HelpCircle className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
                <span>اختبار تفاعلي تجريبي (Quiz)</span>
              </h3>
              {submittedQuiz && (
                <span className="text-xs font-extrabold px-3 py-1 rounded-xl bg-emerald-500/20 text-emerald-700 dark:text-emerald-300">
                  النتيجة: {calculateScore()} / {activity.quiz.length}
                </span>
              )}
            </div>

            <div className="space-y-5">
              {activity.quiz.map((q, qIdx) => {
                const selectedOpt = userAnswers[qIdx];

                return (
                  <div key={q.id || qIdx} className="p-5 rounded-2xl bg-surface-variant/20 border border-outline/15 space-y-3">
                    <div className="flex items-start gap-2 text-xs font-bold text-on-surface">
                      <span className="w-6 h-6 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0">
                        {qIdx + 1}
                      </span>
                      <div className="pt-0.5">
                        <MathText content={q.question} />
                      </div>
                    </div>

                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 pt-1">
                      {q.options.map((optText, oIdx) => {
                        const isSelected = selectedOpt === oIdx;
                        const isCorrectOption = q.correctIndex === oIdx;

                        let optCardStyle = "bg-surface border-outline/20 text-on-surface hover:bg-surface-variant/50";

                        if (submittedQuiz) {
                          if (isCorrectOption) {
                            optCardStyle = "bg-emerald-500/20 border-emerald-500 text-emerald-700 font-bold";
                          } else if (isSelected && !isCorrectOption) {
                            optCardStyle = "bg-error-container/60 border-error text-on-error-container font-bold";
                          }
                        } else if (isSelected) {
                          optCardStyle = "bg-primary/10 border-primary text-primary font-bold shadow-xs";
                        }

                        return (
                          <div
                            key={oIdx}
                            onClick={() => handleSelectAnswer(qIdx, oIdx)}
                            className={`p-3 rounded-xl border transition-all cursor-pointer flex items-center justify-between text-xs ${optCardStyle}`}
                          >
                            <span>
                              <MathText content={optText} />
                            </span>
                            {submittedQuiz && isCorrectOption && (
                              <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                            )}
                            {submittedQuiz && isSelected && !isCorrectOption && (
                              <XCircle className="w-4 h-4 text-error shrink-0" />
                            )}
                          </div>
                        );
                      })}
                    </div>

                    {/* Question Explanation after submission */}
                    {submittedQuiz && q.explanation && (
                      <div className="p-3 rounded-xl bg-surface border border-outline/10 text-[11px] text-on-surface-variant mt-2">
                        <strong className="text-primary block mb-0.5">التوضيح الشارح:</strong>
                        <MathText content={q.explanation} />
                      </div>
                    )}
                  </div>
                );
              })}
            </div>

            {/* Quiz Submit Test Button */}
            <div className="pt-2">
              {!submittedQuiz ? (
                <button
                  type="button"
                  onClick={() => setSubmittedQuiz(true)}
                  className="w-full h-11 rounded-xl bg-emerald-600 text-white font-bold text-xs hover:bg-emerald-700 transition-colors shadow-sm"
                >
                  تأكيد الإجابات واختبار النتيجة
                </button>
              ) : (
                <button
                  type="button"
                  onClick={() => {
                    setSubmittedQuiz(false);
                    setUserAnswers({});
                  }}
                  className="w-full h-11 rounded-xl bg-surface-variant text-on-surface-variant font-bold text-xs hover:bg-surface-variant/80 transition-colors"
                >
                  إعادة الاختبار التجريبي
                </button>
              )}
            </div>
          </div>
        )}
      </div>

      {/* Task B: Interactive PDF Modal Preview with Full-Screen Toggle */}
      {selectedPdfUrl && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4 animate-fadeIn">
          <div
            className={`bg-surface border border-outline/15 shadow-2xl flex flex-col space-y-4 transition-all duration-300 ${
              isFullScreen
                ? "fixed inset-0 z-50 w-screen h-screen max-w-none rounded-none m-0 p-4 sm:p-6"
                : "rounded-3xl p-6 max-w-4xl w-full h-[85vh] animate-scaleUp"
            }`}
          >
            <div className="flex items-center justify-between border-b border-outline/10 pb-3">
              <h3 className="text-sm font-bold text-on-surface flex items-center gap-2">
                <FileText className="w-5 h-5 text-secondary" />
                <span>معاينة ملف PDF المرفق</span>
              </h3>

              <div className="flex items-center gap-2">
                {/* Full Screen Toggle Button */}
                <button
                  type="button"
                  onClick={() => setIsFullScreen(!isFullScreen)}
                  className="p-1.5 rounded-xl text-on-surface-variant hover:bg-surface-variant hover:text-primary transition-colors"
                  title={isFullScreen ? "تصغير النافذة" : "ملء الشاشة"}
                  aria-label={isFullScreen ? "تصغير النافذة" : "ملء الشاشة"}
                >
                  {isFullScreen ? <Minimize2 className="w-5 h-5" /> : <Maximize2 className="w-5 h-5" />}
                </button>

                <a
                  href={selectedPdfUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-3 py-1.5 rounded-xl bg-primary/10 text-primary text-xs font-bold hover:bg-primary/20 transition-colors flex items-center gap-1"
                >
                  <span>فتح في نافذة جديدة</span>
                  <ExternalLink className="w-3.5 h-3.5" />
                </a>

                <button
                  type="button"
                  onClick={() => {
                    setSelectedPdfUrl(null);
                    setIsFullScreen(false);
                  }}
                  className="p-1.5 rounded-xl text-on-surface-variant hover:bg-surface-variant transition-colors"
                  aria-label="إغلاق النافذة"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>
            </div>

            <div className="flex-1 w-full rounded-2xl overflow-hidden bg-surface-variant/20 border border-outline/10">
              <iframe
                src={formatPdfEmbedUrl(selectedPdfUrl)}
                allow="autoplay"
                className={`w-full ${isFullScreen ? "h-[calc(100vh-100px)]" : "h-[600px]"} rounded-xl border-none`}
                title="PDF Preview"
              />
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default StudentPreview;
