/**
 * Format PDF URL for safe iframe embedding.
 * Converts Google Drive '/view...' links to '/preview' to resolve 403 / refused to frame errors.
 */
export function formatPdfEmbedUrl(url: string): string {
  if (!url || typeof url !== "string") return "";

  let trimmed = url.trim();

  // Handle Google Drive URLs
  if (trimmed.includes("drive.google.com")) {
    if (trimmed.includes("/preview")) {
      return trimmed;
    }
    // Replace /view and any query string after /view with /preview
    trimmed = trimmed.replace(/\/view(\?.*)?$/, "/preview");
    trimmed = trimmed.replace(/\/view\?.*/, "/preview");
  }

  return trimmed;
}

/**
 * Format YouTube URL for safe iframe embedding.
 * Converts watch/share URLs (youtube.com/watch?v=ID or youtu.be/ID) into embed format (youtube.com/embed/ID).
 */
export function formatYouTubeUrl(url: string): string {
  if (!url || typeof url !== "string") return "";

  const trimmed = url.trim();

  // Pattern 1: https://www.youtube.com/watch?v=ID or https://youtube.com/watch?v=ID
  const watchMatch = trimmed.match(/(?:youtube\.com\/watch\?v=)([a-zA-Z0-9_-]+)/);
  if (watchMatch && watchMatch[1]) {
    return `https://www.youtube.com/embed/${watchMatch[1]}`;
  }

  // Pattern 2: https://youtu.be/ID
  const shortMatch = trimmed.match(/(?:youtu\.be\/)([a-zA-Z0-9_-]+)/);
  if (shortMatch && shortMatch[1]) {
    return `https://www.youtube.com/embed/${shortMatch[1]}`;
  }

  // Pattern 3: Already an embed URL (e.g. https://www.youtube.com/embed/ID)
  const embedMatch = trimmed.match(/(?:youtube\.com\/embed\/)([a-zA-Z0-9_-]+)/);
  if (embedMatch && embedMatch[1]) {
    return `https://www.youtube.com/embed/${embedMatch[1]}`;
  }

  return trimmed;
}

export interface LatexSegment {
  type: "text" | "inline" | "block";
  content: string;
}

/**
 * Parses a string containing LaTeX delimiters ($inline$ or $$block$$) into structured segments.
 * Uses robust regex: /(\$\$[\s\S]*?\$\$|\$[\s\S]*?\$)/g
 */
export function parseLatexSegments(text: string): LatexSegment[] {
  if (!text || typeof text !== "string") return [];

  // Clean non-breaking spaces generated by Quill Editor
  const sanitizedText = text.replace(/&nbsp;/g, " ").replace(/&#160;/g, " ");

  const regex = /(\$\$[\s\S]*?\$\$|\$[\s\S]*?\$)/g;
  const parts = sanitizedText.split(regex);

  return parts
    .map((part) => {
      if (!part) return null;
      if (part.startsWith("$$") && part.endsWith("$$")) {
        return { type: "block" as const, content: part.slice(2, -2).trim() };
      } else if (part.startsWith("$") && part.endsWith("$")) {
        return { type: "inline" as const, content: part.slice(1, -1).trim() };
      }
      return { type: "text" as const, content: part };
    })
    .filter((segment): segment is LatexSegment => segment !== null);
}
